<?php

$jos_menu_data = [
	/*Автоистория/История Daewoo*/
	0 => [
		'id' => '27',
		'name' => 'История Daewoo',
		'alias' => 'istorija-daewoo',
		'published' => '1',
		'parent' => '26',
		'ordering' => '1',
	],
	1 => [
		'id' => '2',
		'name' => 'Главная',
		'alias' => 'home',
		'published' => '1',
		'parent' => '0',
		'ordering' => '1',
	],
	2 => [
		'id' => '3',
		'name' => 'Автоновости',
		'alias' => 'avtonovosti',
		'published' => '1',
		'parent' => '0',
		'ordering' => '5',
	],
	3 => [
		'id' => '4',
		'name' => 'Статьи',
		'alias' => 'stati',
		'published' => '1',
		'parent' => '0',
		'ordering' => '10',
	],
	4 => [
		'id' => '5',
		'name' => 'Файлы',
		'alias' => 'fajly',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '2',
	],
	5 => [
		'id' => '6',
		'name' => 'Журналы',
		'alias' => 'zhurnaly',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '4',
	],
	6 => [
		'id' => '7',
		'name' => 'Книги',
		'alias' => 'knigi',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '6',
	],
	7 => [
		'id' => '8',
		'name' => 'Образы дисков',
		'alias' => 'obrazy-diskov',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '8',
	],
	8 => [
		'id' => '9',
		'name' => 'Контакты',
		'alias' => 'kontakty',
		'published' => '1',
		'parent' => '0',
		'ordering' => '13',
	],
	9 => [
		'id' => '10',
		'name' => 'Карта сайта',
		'alias' => 'karta-sajta',
		'published' => '0',
		'parent' => '0',
		'ordering' => '15',
	],
	10 => [
		'id' => '26',
		'name' => 'Автоистория',
		'alias' => 'avtoistorija',
		'published' => '1',
		'parent' => '0',
		'ordering' => '7',
	],
	11 => [
		'id' => '25',
		'name' => 'О сайте',
		'alias' => 'o-sajte',
		'published' => '1',
		'parent' => '0',
		'ordering' => '3',
	],
	12 => [
		'id' => '42',
		'name' => 'История УАЗ',
		'alias' => 'istorija-uaz',
		'published' => '1',
		'parent' => '26',
		'ordering' => '10',
	],
	/*Статьи/Daewoo Lanos, Nexia, Matiz, Sens*/
	13 => [
		'id' => '24',
		'name' => 'Daewoo Lanos, Nexia, Matiz, Sens',
		'alias' => 'daewoo',
		'published' => '1',
		'parent' => '4',
		'ordering' => '3',
	],
	/*Статьи/ВАЗ 2108, ВАЗ 2109, ВАЗ 2110, ВАЗ 1117, ВАЗ 2170*/
	14 => [
		'id' => '23',
		'name' => 'ВАЗ 2108, ВАЗ 2109, ВАЗ 2110, ВАЗ 1117, ВАЗ 2170',
		'alias' => 'vaz-2108-vaz-2109-vaz-2110',
		'published' => '1',
		'parent' => '4',
		'ordering' => '2',
	],
	15 => [
		'id' => '21',
		'name' => 'Советы',
		'alias' => 'sovety',
		'published' => '1',
		'parent' => '0',
		'ordering' => '12',
	],
	/*Статьи/ВАЗ 2101, ВАЗ 2102, ВАЗ 2105, ВАЗ 2106, ВАЗ 2107*/
	16 => [
		'id' => '22',
		'name' => 'ВАЗ 2101, ВАЗ 2102, ВАЗ 2105, ВАЗ 2106, ВАЗ 2107',
		'alias' => 'vaz-2101-vaz-2106-vaz-2107',
		'published' => '1',
		'parent' => '4',
		'ordering' => '1',
	],
	17 => [
		'id' => '20',
		'name' => 'VAZ 2101, 2106, 2107',
		'alias' => 'vaz-2101-2106-2107',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '9',
	],
	18 => [
		'id' => '19',
		'name' => 'VAZ 2101, 2106, 2107',
		'alias' => 'vaz-2101-2106-2107',
		'published' => '-2',
		'parent' => '0',
		'ordering' => '11',
	],
	19 => [
		'id' => '28',
		'name' => 'История Skoda',
		'alias' => 'istorija-skoda',
		'published' => '1',
		'parent' => '26',
		'ordering' => '2',
	],
	20 => [
		'id' => '29',
		'name' => 'История Nissan',
		'alias' => 'istorija-nissan',
		'published' => '1',
		'parent' => '26',
		'ordering' => '3',
	],
	21 => [
		'id' => '30',
		'name' => 'История Hyundai',
		'alias' => 'istorija-hyundai',
		'published' => '1',
		'parent' => '26',
		'ordering' => '4',
	],
	22 => [
		'id' => '31',
		'name' => 'История Citroen',
		'alias' => 'istorija-citroen',
		'published' => '1',
		'parent' => '26',
		'ordering' => '5',
	],
	23 => [
		'id' => '33',
		'name' => 'История Mazda',
		'alias' => 'istorija-mazda',
		'published' => '1',
		'parent' => '26',
		'ordering' => '6',
	],
	24 => [
		'id' => '34',
		'name' => 'История ВАЗ',
		'alias' => 'istorija-vaz',
		'published' => '1',
		'parent' => '26',
		'ordering' => '7',
	],
	25 => [
		'id' => '35',
		'name' => 'История Kia',
		'alias' => 'istorija-kia',
		'published' => '1',
		'parent' => '26',
		'ordering' => '8',
	],
	26 => [
		'id' => '36',
		'name' => 'История Chevrolet',
		'alias' => 'istorija-chevrolet',
		'published' => '1',
		'parent' => '26',
		'ordering' => '9',
	],
	/*Статьи/Таврия, Славута, ЗАЗ-1102*/
	27 => [
		'id' => '39',
		'name' => 'Таврия, Славута, ЗАЗ-1102',
		'alias' => 'tavrija-slavuta-zaz1102',
		'published' => '1',
		'parent' => '4',
		'ordering' => '5',
	],
	/*Статьи/Mitsubishi (Мицубиси)*/
	28 => [
		'id' => '38',
		'name' => 'Mitsubishi (Мицубиси)',
		'alias' => 'mitsubishi-micubisi-',
		'published' => '1',
		'parent' => '4',
		'ordering' => '4',
	],
	29 => [
		'id' => '40',
		'name' => 'Вопрос-Ответ',
		'alias' => 'voprosotvet',
		'published' => '1',
		'parent' => '0',
		'ordering' => '14',
	],
	30 => [
		'id' => '41',
		'name' => 'Карта сайта',
		'alias' => 'karta-sajta',
		'published' => '1',
		'parent' => '0',
		'ordering' => '3',
	],
	31 => [
		'id' => '43',
		'name' => 'Discussions',
		'alias' => 'discussions',
		'published' => '1',
		'parent' => '0',
		'ordering' => '16',
	],
	32 => [
		'id' => '44',
		'name' => 'Вход/Регистрация',
		'alias' => 'vhodregistracija',
		'published' => '1',
		'parent' => '0',
		'ordering' => '1',
	],
	33 => [
		'id' => '45',
		'name' => 'Взаимопомощь',
		'alias' => 'vzaimopomosch',
		'published' => '1',
		'parent' => '0',
		'ordering' => '2',
	],
	34 => [
		'id' => '46',
		'name' => 'Гараж',
		'alias' => 'garazh',
		'published' => '1',
		'parent' => '0',
		'ordering' => '3',
	],
	35 => [
		'id' => '47',
		'name' => 'История ГАЗ',
		'alias' => 'istorija-gaz',
		'published' => '1',
		'parent' => '26',
		'ordering' => '11',
	],
	36 => [
		'id' => '48',
		'name' => 'История ЗАЗ',
		'alias' => 'istorija-zaz',
		'published' => '1',
		'parent' => '26',
		'ordering' => '12',
	],
	37 => [
		'id' => '49',
		'name' => 'Контакты',
		'alias' => 'kontakty',
		'published' => '0',
		'parent' => '0',
		'ordering' => '1',
	],
	38 => [
		'id' => '50',
		'name' => 'Гараж',
		'alias' => 'garazh',
		'published' => '1',
		'parent' => '0',
		'ordering' => '16',
	],
	39 => [
		'id' => '52',
		'name' => 'ЧаВо',
		'alias' => 'chavo',
		'published' => '1',
		'parent' => '0',
		'ordering' => '2',
	],
	/*Статьи/Chery (Чери)*/
	40 => [
		'id' => '51',
		'name' => 'Chery (Чери)',
		'alias' => 'chery',
		'published' => '1',
		'parent' => '4',
		'ordering' => '6',
	],
	41 => [
		'id' => '53',
		'name' => 'Вопрос-Ответ',
		'alias' => 'voprosotvet',
		'published' => '0',
		'parent' => '0',
		'ordering' => '17',
	],
	42 => [
		'id' => '54',
		'name' => 'Daewoo Lanos, Nexia, Matiz, Sens, Nubira',
		'alias' => 'daewoo-lanos-nexia-matiz-sens-nubira',
		'published' => '1',
		'parent' => '53',
		'ordering' => '1',
	],
	43 => [
		'id' => '55',
		'name' => 'Ваз-2101, Ваз-2104, Ваз-2105, Ваз-2106, Ваз-2107, Классика',
		'alias' => 'vaz2101-vaz2104-vaz2105-vaz2106-vaz2107-klassika',
		'published' => '1',
		'parent' => '53',
		'ordering' => '2',
	],
	44 => [
		'id' => '56',
		'name' => 'Ваз-2108, Ваз-21099, Ваз-2110, Ваз-2115, Ваз-1117 Калина, Ваз-2170 Приора',
		'alias' => 'vaz2108-vaz21099-vaz2110-vaz2115-vaz1117-kalina-vaz2170-priora',
		'published' => '1',
		'parent' => '53',
		'ordering' => '3',
	],
];

echo "<pre>\n";
foreach($jos_menu_data as $item_key => $item) {
	if($item['parent'] == '26') {
		echo "$item_key => [\n";
		foreach ($item as $key => $value) {
			echo "    '$key' => '$value',\n";
		}  	
		echo "],\n";
	}
}
echo "\n</pre>";